version: "3.8"

services:
  app:
    container_name: quran-audio
    image: quran-audio
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000